Prepare for sync

diff --git a/modules/profile/files/_github/workflows/tag_deploy_rubygem__github-rpms.yml b/modules/profile/files/_github/workflows/tag_deploy_rubygem__github-rpms.yml
--- a/modules/profile/files/_github/workflows/tag_deploy_rubygem__github-rpms.yml
+++ b/modules/profile/files/_github/workflows/tag_deploy_rubygem__github-rpms.yml
@@ -1,6 +1,4 @@
-# When SemVer tag is pushed: create GitHub release & publish gem to rubygems.org
-#
-# This workflow's jobs are only triggered in repos under the `simp` organization
+# Build & Deploy GitHub release & RubyGem RPM when a SemVer tag is pushed
 # ------------------------------------------------------------------------------
 #
 #             NOTICE: **This file is maintained with puppetsync**
@@ -13,9 +11,13 @@
 #
 # This pipeline uses the following GitHub Action Secrets:
 #
-#   GitHub Secret variable    Type      Notes
-#   ------------------------  --------  ----------------------------------------
-#   RUBYGEMS_API_KEY          Required
+#   GitHub Secret variable               Notes
+#   -------------------------------      ---------------------------------------
+#   SIMP_CORE_REF_FOR_BUILDING_RPMS      simp-core ref (tag) to use to build
+#                                        RPMs with `rake pkg:single`
+#   SIMP_DEV_GPG_SIGNING_KEY             GPG signing key's secret key
+#   SIMP_DEV_GPG_SIGNING_KEY_ID          User ID (name) of signing key
+#   SIMP_DEV_GPG_SIGNING_KEY_PASSPHRASE  Passphrase to use GPG signing key
 #
 # ------------------------------------------------------------------------------
 #
@@ -23,21 +25,8 @@
 #
 # * The CHANGLOG text is altered to remove RPM-style date headers, which don't
 #   render well as markdown on the GitHub release pages
-#
-# * By default, the gem is built and released using the standard rake tasks
-#   from "bundler/gem_tasks".  To override these, create a JSON file at
-#   `.github/workflows.local.json`, using the following format:
-#
-#         {
-#           "gem_build_command": "bundle exec rake build",
-#           "gem_release_command": "bundle exec rake build release:rubygem_push",
-#           "gem_pkg_dir": "pkg"
-#         }
-#
-#   All keys are optional.
-#
 ---
-name: 'Tag: Release to GitHub & rubygems.org'
+name: 'Tag: Release to GitHub +ibuild /attach RPMs'
 
 on:
   push:
@@ -56,7 +45,6 @@ jobs:
     outputs:
       build_command: ${{ steps.commands.outputs.build_command }}
       release_command: ${{ steps.commands.outputs.release_command }}
-      pkg_dir: ${{ steps.commands.outputs.pkg_dir }}
     steps:
       - name: "Assert '${{ github.ref }}' is a tag"
         run: '[[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is not a tag: ${GITHUB_REF}"; exit 1 ; }'
@@ -67,43 +55,25 @@ jobs:
       - name: Determing build and release commands
         id: commands
         run: |
-          # By default, these are the standard tasks from "bundler/gem_tasks"
-          # To override them in the LOCAL_WORKFLOW_CONFIG_FILE
+          # By default, this is the standard task from "bundler/gem_tasks"
+          # To override it, add the new command to LOCAL_WORKFLOW_CONFIG_FILE
           GEM_BUILD_COMMAND='bundle exec rake build'
-          GEM_RELEASE_COMMAND='bundle exec rake build release:rubygem_push'
-          GEM_PKG_DIR='pkg'
-          if jq -r '. | keys' "$LOCAL_WORKFLOW_CONFIG_FILE" 2>/dev/null | \
-              grep -w '"gem_pkg_dir"' &> /dev/null; then
-            GEM_PKG_DIR="$(jq -r .gem_pkg_dir "$LOCAL_WORKFLOW_CONFIG_FILE" )"
-          fi
           if jq -r '. | keys' "$LOCAL_WORKFLOW_CONFIG_FILE" 2>/dev/null | \
               grep -w '"gem_build_command"' &> /dev/null; then
-            GEM_BUILD_COMMAND="$(jq -r .gem_build_command "$LOCAL_WORKFLOW_CONFIG_FILE" )"
-          fi
-          if jq -r '. | keys' "$LOCAL_WORKFLOW_CONFIG_FILE" 2>/dev/null | \
-              grep -w '"gem_release_command"' &> /dev/null; then
-            GEM_RELEASE_COMMAND="$(jq -r .gem_release_command "$LOCAL_WORKFLOW_CONFIG_FILE" )"
+            GEM_BUILD_COMMAND="$(jq .gem_build_command "$LOCAL_WORKFLOW_CONFIG_FILE" )"
           fi
           echo "::set-output name=build_command::${GEM_BUILD_COMMAND}"
-          echo "::set-output name=pkg_dir::${GEM_PKG_DIR}"
           echo "::set-output name=release_command::${GEM_RELEASE_COMMAND}"
       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.5
           bundler-cache: true
       - name: Test build the package
-        env:
-          GEM_BUILD_COMMAND: ${{ steps.commands.outputs.build_command }}
-        run: "$GEM_BUILD_COMMAND"
+        run: "${{ steps.commands.outputs.build_command }}"
       - name: "Assert '${{ github.ref }}' matches the package version"
         run: |
           tag="${GITHUB_REF/refs\/tags\//}"
-          [ -d  "${{ steps.commands.outputs.pkg_dir }}" ] || \
-             { echo "::error ::No directory found at ${{ steps.commands.outputs.pkg_dir }}/" ; exit 3 ; }
-          ls -1 "${{ steps.commands.outputs.pkg_dir }}"/*.gem || \
-             {  echo "::error ::No gem file found at ${{ steps.commands.outputs.pkg_dir }}/*.gem" ; exit 2 ; }
-          [ -f "${{ steps.commands.outputs.pkg_dir }}"/*-${tag}.gem ] || \
-             { echo "::error ::tag '${tag}' does not match package $(ls -1 ${{ steps.commands.outputs.pkg_dir }}/*.gem)"; exit 1 ; }
+          [ -f pkg/*-${tag}.gem ] || { echo "::error ::tag '${tag}' does not match package $(ls -1 pkg/*.gem)"; exit 1 ; }
 
   create-github-release:
     name: Deploy GitHub Release
@@ -149,44 +119,34 @@ jobs:
           draft: false
           prerelease: false
 
-  deploy-rubygem:
-    name: Deploy RubyGem Release
-    needs: [ releng-checks ]
+  build-and-attach-rpms:
+    name: Trigger RPM release
+    needs: [ create-github-release ]
     if: github.repository_owner == 'simp'
     runs-on: ubuntu-18.04
     env:
-      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
-      BUILD_COMMAND: ${{ needs.releng-checks.outputs.build_command }}
-      RELEASE_COMMAND: ${{ needs.releng-checks.outputs.release_command }}
-      PKG_DIR: ${{ needs.releng-checks.outputs.pkg_dir }}
+      TARGET_REPO: ${{ github.repository }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Get tag & annotation info (${{github.ref}})
+        id: tag-check
+        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
+      - name: Trigger RPM release workflow
+        uses: actions/github-script@v4
+        env:
+          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
+          TARGET_TAG: ${{ steps.tag-check.outputs.tag }}
         with:
-          ref: ${{ github.ref }}
-          clean: true
-      - uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 2.5
-          bundler-cache: true
-      - name: Build RubyGem
-        run: |
-          echo "Setting up file permissions..."
-          chmod -R go=u-w .
-
-          echo "Running '$BUILD_COMMAND'..."
-          $BUILD_COMMAND
-
-      - name: Release RubyGem
-        run: |
-          echo "Setting up gem credentials..."
-          mkdir -p ~/.gem
-
-          cat << EOF > ~/.gem/credentials
-          ---
-          :rubygems_api_key: ${RUBYGEMS_API_KEY}
-          EOF
-          chmod 0600 ~/.gem/credentials
-
-          echo "Running '$RELEASE_COMMAND'..."
-          $RELEASE_COMMAND
+          github-token: ${{ secrets.SIMP_AUTO_GITHUB_TOKEN__REPO_SCOPE }}
+          script: |
+            const [owner, repo] = process.env.TARGET_REPO.split('/')
+            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
+              owner: owner,
+              repo: repo,
+              workflow_id: 'release_rpms.yml',
+              ref: process.env.DEFAULT_BRANCH,
+              inputs: {
+                release_tag: process.env.TARGET_TAG
+              }
+            }).then( (result) => {
+              console.log( `== Submitted workflow dispatch: status ${result.status}` )
+            })
