Improve GHA RPM build workflows
- GHA `tag_deploy*.yml` workflows now use the proper `'yes'` and `'no'`
  arguments for `clean:` and `clobber:` when dispatching the workflow
  `release_rpms.yml`
- Collapsed separate EL7 and EL8 build-and-attach RPM stages into a
  single GHA stage with a matrix
- Fail GHA build action on malformed tag name
- Move `ubuntu-18.04` images to `ubuntu-latest`
- Normalized GHA workflows across all project types
- Fixed pre-release decision bug in `deploy-to-puppetforge` stage

diff --git a/modules/profile/files/_github/workflows/tag_deploy_github-only.yml b/modules/profile/files/_github/workflows/tag_deploy_github-only.yml
--- a/modules/profile/files/_github/workflows/tag_deploy_github-only.yml
+++ b/modules/profile/files/_github/workflows/tag_deploy_github-only.yml
@@ -26,7 +26,9 @@ jobs:
   create-github-release:
     name: Deploy GitHub Release
     if: github.repository_owner == 'simp'
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-latest
+    outputs:
+      prerelease: ${{ steps.tag-check.outputs.prerelease }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -34,6 +36,7 @@ jobs:
           ref: ${{ github.ref }}
           clean: true
           fetch-depth: 0
+
       - name: Get tag & annotation info (${{github.ref}})
         id: tag-check
         run: |
@@ -41,7 +44,19 @@ jobs:
           annotation="$(git for-each-ref "$GITHUB_REF" --format='%(contents)' --count=1)"
           annotation_title="$(echo "$annotation" | head -1)"
 
+
+          if [[ "$tag" =~ ^(simp-|v)?[0-9]+\.[0-9]+\.[0-9]+(-(rc|alpha|beta|pre|post)?([0-9]+)?)?$ ]]; then
+            if [ -n "${BASH_REMATCH[2]}" ]; then
+              prerelease=yes
+              annotation_title="Pre-release of ${tag}"
+            fi
+          else
+            printf '::error ::Release Tag format is not SemVer, X.Y.Z-R, X.Y.Z-<prerelease>: "%s"\n' "$RELEASE_TAG"
+            exit 88
+          fi
+
           echo "::set-output name=tag::${tag}"
+          echo "::set-output name=prerelease::${prerelease}"
           echo "::set-output name=annotation_title::${annotation_title}"
 
           # Prepare annotation body as a file for the next step
@@ -63,5 +78,5 @@ jobs:
           tag_name: ${{ github.ref }}
           release_name: ${{ steps.tag-check.outputs.annotation_title }}
           body_path: /tmp/annotation.body
+          prerelease: ${{ steps.tag-check.outputs.prerelease  == 'yes'}}
           draft: false
-          prerelease: false
