(SIMP-9407) GHA: rubygem release override fixes

diff --git a/site-modules/profile/files/_github/workflows/tag_deploy_rubygem__github-only.yml b/site-modules/profile/files/_github/workflows/tag_deploy_rubygem__github-only.yml
--- a/site-modules/profile/files/_github/workflows/tag_deploy_rubygem__github-only.yml
+++ b/site-modules/profile/files/_github/workflows/tag_deploy_rubygem__github-only.yml
@@ -1,4 +1,6 @@
 # Build & Deploy release when a SemVer tag is pushed
+#
+# This workflow's jobs are only triggered in repos under the `simp` organization
 # ------------------------------------------------------------------------------
 #
 # This pipeline uses the following GitHub Action Secrets:
@@ -28,6 +30,7 @@ env:
 jobs:
   releng-checks:
     name: "RELENG checks"
+    if: github.repository_owner == 'simp'
     runs-on: ubuntu-18.04
     outputs:
       build_command: ${{ steps.commands.outputs.build_command }}
@@ -57,10 +60,15 @@ jobs:
           bundler-cache: true
       - name: Test build the package
         run: "${{ steps.commands.outputs.build_command }}"
+      - name: "Assert '${{ github.ref }}' matches the package version"
+        run: |
+          tag="${GITHUB_REF/refs\/tags\//}"
+          [ -f pkg/*-${tag}.gem ] || { echo "::error ::tag '${tag}' does not match package $(ls -1 pkg/*.gem)"; exit 1 ; }
 
   create-github-release:
     name: Deploy GitHub Release
     needs: [ releng-checks ]
+    if: github.repository_owner == 'simp'
     runs-on: ubuntu-18.04
     steps:
       - name: Checkout code
